image: "node:14"
pages:
  stage: deploy
  script:
    - npm install --progress=false
    - npm run build
    - mv dist public
  artifacts:
    expire_in: 1 day
    paths:
      - public
  only:
    - master

